language: cpp

cache:
  directories:
    - vcpkg
    - build/vcpkg_installed

jobs:
  include:
    - os: linux
      dist: focal
      compiler: gcc
      env:
        - TRAVIS_BUILD_DOCS=1
        - MATRIX_EVAL="CC=gcc-10 && CXX=g++-10"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-10
            - g++-10
            - doxygen
            - graphviz
            - i2c-tools
            - libi2c-dev

before_script:
  - eval "${MATRIX_EVAL}"

script:
  - mkdir -p build
  - cd build
  - cmake -DENABLE_COVERAGE:BOOL=TRUE -DENABLE_TESTING=ON -DENABLE_DOXYGEN=ON ../
  - cmake --build . --target tests
  - ctest

after_success:
  # Generate the docs only if master, the travis_build_docs is true and we can use secure variables
  - >-
    if [[ "$TRAVIS_BRANCH" = "master" && -n "$TRAVIS_BUILD_DOCS" && "$TRAVIS_PULL_REQUEST" = "false" ]] ; then
      cd $PROJECT_DIR_ABS
      source .ci/setup-ssh.sh || travis_terminate 1

      GH_REPO_ORG=`echo $TRAVIS_REPO_SLUG | cut -d "/" -f 1`
      GH_REPO_NAME=`echo $TRAVIS_REPO_SLUG | cut -d "/" -f 2`
      git clone -b gh-pages git@github.com:$GH_REPO_ORG/$GH_REPO_NAME.git code_docs
      cd code_docs/
      git config --global push.default simple
      git config user.name "Travis CI"
      git config user.email "travis@travis-ci.org"
      git reset --hard `git rev-list --max-parents=0 --abbrev-commit HEAD`

      echo 'Generating Doxygen code documentation...'
      cmake --build ../build target doxygen-docs
      cp -r ../html/ .

      echo 'Uploading documentation to the gh-pages branch...'
      git add --all
      git commit -m "Deploy code docs to GitHub Pages Travis build: ${TRAVIS_BUILD_NUMBER}" -m "Commit: ${TRAVIS_COMMIT}"
      git push --force "git@github.com:$GH_REPO_ORG/$GH_REPO_NAME.git" > /dev/null 2>&1
    fi
