ads1115: ADS1115::ADS1115 Class Reference
ADS1115::ADS1115 Class Reference
#include "ads1115.hpp"
Public Member Functions
ADS1115 (const std::filesystem::path &fs_dev, const ADDR addr)
~ADS1115 ()
Destroys the object that represents the ADS1115.
ADDR getADDR () const
void setADDR (const ADDR addr)
int16_t read () const
double readVoltage () const
void reset ()
double toVoltage (const int16_t value) const
int16_t fromVoltage (const double value) const
Config readRegConfig ()
Config getRegConfig () const
void setRegConfig (const Config config)
Threshold readRegThreshold ()
Threshold getRegThreshold () const
void setRegThreshold (const Threshold threshold)
Private Member Functions
uint16_t read_word (const uint8_t reg_addr) const
void write_word (const uint8_t reg_addr, const uint16_t value) const
Private Attributes
const int m_posix_handle
The linux filedescriptor to the i2c device in use.
ADDR m_addr
The i2c bus address of the ADS1115.
Config m_config {}
The current configuration of the ADS1115.
Threshold m_threshold {}
The current configuration of the threshold registers.
Detailed Description
This class describes the ADS1115. The data sheet of the ADS1115 can be fond at https://cdn-shop.adafruit.com/datasheets/ads1115.pdf.
Definition at line 19 of file ads1115.hpp.
Constructor & Destructor Documentation
ADS1115()
ADS1115::ADS1115::ADS1115 (const std::filesystem::path & fs_dev, const ADDR addr)
Creates the object to represent the ADS1115.
This will open the device given by fs_dev and try to connect to the given i2c bus address. The the configuration register of the ADS1115 is loaded and stored in the object.
Parameters
fs_dev std::filesystem::path to the i2c bus device file.
addr Address of the ADS1115 on the i2c bus.
Definition at line 32 of file ads1115.cpp.
         : m_posix_handle(open(fs_dev.c_str(), O_RDWR))
     {
         if (m_posix_handle < 0) {
             throw std::runtime_error("Unable to open i2c device.");
         }
         setADDR(addr);
     }
~ADS1115()
ADS1115::ADS1115::~ADS1115 ()
Destroys the object that represents the ADS1115.
Definition at line 41 of file ads1115.cpp.
     {
         close(m_posix_handle);
     }
Member Function Documentation
fromVoltage()
int16_t ADS1115::ADS1115::fromVoltage (const double value) const
Converts a voltage value to a value returned by read(),
Uses the current PGA setting for the conversion.
Parameters
value The value to be converted.
Returns
The value in the same representation as returned by read().
Definition at line 104 of file ads1115.cpp.
     {
         return static_cast<int16_t>(value * 32768 / pga_voltage_map.at(m_config.pga));
     }
References ADS1115::pga_voltage_map.
getADDR()
ADDR ADS1115::ADS1115::getADDR () const
Returns the address of the ADS1115 that is currently used.
Returns
ADDR that represents the currently used address.
Definition at line 46 of file ads1115.cpp.
     {
         return m_addr;
     }
Referenced by TEST().
getRegConfig()
Config ADS1115::ADS1115::getRegConfig () const
Returns the currently stored configuration of the ADS1115 without hiting the chip.
Returns
A Config object representing the content of the config register.
Definition at line 121 of file ads1115.cpp.
     {
         return m_config;
     }
Referenced by TEST().
getRegThreshold()
Threshold ADS1115::ADS1115::getRegThreshold () const
Returns the currently stored threshold registers of the ADS1115 whithout hiting the chip.
Returns
A Threshold object representing the contents of the threshold registers.
Definition at line 150 of file ads1115.cpp.
     {
         return m_threshold;
     }
Referenced by TEST().
read()
int16_t ADS1115::ADS1115::read () const
Read the current value of the conversion register of the ADS1115. If the ADS1115 is in single conversion mode a new conversion will be started an the function returns when the conversion is done.
Returns
The value of the conversion register.
Definition at line 66 of file ads1115.cpp.
     {
         if (m_config.mode == MODE::SINGLE_CONV) {
             // to start a conversion in single conversion mode the MSB of the config
             // register has to be set
             write_word(conf_reg_addr, m_config.to_bytes() | 0x8000);
             // when the conversion starts the ADS1115 resets the MSB and sets it when the conversion
             // is done
             while (!(read_word(conf_reg_addr) & 0x8000)) {
                 // poll every millisecond, as the shortest conversion the device can do takes 1.2ms
                 std::this_thread::sleep_for(std::chrono::milliseconds(1));
             }
         }
         uint16_t data = read_word(conv_reg_addr);
         return util::bit_cast<int16_t, uint16_t>(data);
     }
References ADS1115::conf_reg_addr, ADS1115::conv_reg_addr, and ADS1115::SINGLE_CONV.
read_word()
uint16_t ADS1115::ADS1115::read_word (const uint8_t reg_addr) const private
Read a 16 bit value from a register.
Parameters
reg_addr The address of the register to be read.
Definition at line 162 of file ads1115.cpp.
     {
         int32_t data = i2c_smbus_read_word_data(m_posix_handle, reg_addr);
         if (0 > data) {
             throw std::runtime_error("Error reading value from i2c device.");
         }
         return util::from_device_repr(static_cast<uint16_t>(data));
     }
References ADS1115::util::from_device_repr().
readRegConfig()
Config ADS1115::ADS1115::readRegConfig ()
Read the config register of the ADS1115.
Reads the current value of the config register of the ADS1115 and updates the internal object representation of the config.
Returns
A Config object representing the content of the config register.
Definition at line 113 of file ads1115.cpp.
     {
         const uint16_t config_word = read_word(conf_reg_addr);
         Config config(config_word);
         m_config = config;
         return config;
     }
References ADS1115::conf_reg_addr.
readRegThreshold()
Threshold ADS1115::ADS1115::readRegThreshold ()
Read the threshold registers of the ADS1115.
Reads the current value of the threshold registers of the ADS1115 and updates the internal object representation.
Returns
A Threshold object representing the contents of the threshold registers.
Definition at line 136 of file ads1115.cpp.
     {
         uint16_t low_threshold = read_word(lo_thresh_reg_addr);
         uint16_t high_threshold = read_word(hi_thresh_reg_addr);
         Threshold threshold {
             util::bit_cast<int16_t, uint16_t>(low_threshold),
             util::bit_cast<int16_t, uint16_t>(high_threshold),
         };
         m_threshold = threshold;
         return threshold;
     }
References ADS1115::hi_thresh_reg_addr, and ADS1115::lo_thresh_reg_addr.
readVoltage()
double ADS1115::ADS1115::readVoltage () const
Read the current voltage measured by the ADS1115. If the ADS1115 is in single conversion mode a new conversion will be started an the function returns when the conversion is done.
Returns
The voltage value.
Definition at line 85 of file ads1115.cpp.
     {
         return toVoltage(read());
     }
reset()
void ADS1115::ADS1115::reset ()
Resets the device to it's default state.
Definition at line 90 of file ads1115.cpp.
     {
         Config config {};
         setRegConfig(config);
         Threshold threshold {};
         setRegThreshold(threshold);
     }
Referenced by TEST().
setADDR()
void ADS1115::ADS1115::setADDR (const ADDR addr)
Sets the address of the ADS1115 to be used. After setting the new address it loads the config register of the ADS1115 and stores it.
Parameters
addr The address of the ADS1115 to be used.
Definition at line 51 of file ads1115.cpp.
     {
         m_addr = addr;
         // For this device it seems to be impossible to check if the a ADS1115 is listening on the
         // address. This is due to the fact that ioctl returns 0 as long as a ADS1115 is connected
         // and one of the possible addresses is supplied.
         if (ioctl(m_posix_handle, I2C_SLAVE, static_cast<uint8_t>(m_addr)) < 0) {
             // FIXME turn into a device_error
             throw std::runtime_error("Couldn't find device on address!");
         }
         readRegConfig();
         readRegThreshold();
     }
Referenced by TEST().
setRegConfig()
void ADS1115::ADS1115::setRegConfig (const Config config)
Sets the configuration of the ADS1115.
Updates the internal object representation of the configuration and writes it to the config register of the ADS1115.
Parameters
config A Config object representing the content of the config register.
Definition at line 126 of file ads1115.cpp.
     {
         write_word(conf_reg_addr, m_config.to_bytes());
         m_config = config;
     }
References ADS1115::conf_reg_addr.
setRegThreshold()
void ADS1115::ADS1115::setRegThreshold (const Threshold threshold)
Sets the threshold registers of the ADS1115.
Updates the internal object representation of the configuration and writes it to the threshold registers of the ADS1115.
Parameters
threshold A Threshold object representing the contents of the threshold registers.
Definition at line 155 of file ads1115.cpp.
     {
         write_word(lo_thresh_reg_addr, util::bit_cast<uint16_t, int16_t>(threshold.getLow()));
         write_word(hi_thresh_reg_addr, util::bit_cast<uint16_t, int16_t>(threshold.getHigh()));
         m_threshold = threshold;
     }
References ADS1115::Threshold::getHigh(), ADS1115::Threshold::getLow(), ADS1115::hi_thresh_reg_addr, and ADS1115::lo_thresh_reg_addr.
toVoltage()
double ADS1115::ADS1115::toVoltage (const int16_t value) const
Converts a value returned by read() to a Voltage.
Uses the current PGA setting for the conversion.
Parameters
value The value to be converted.
Returns
The voltage value of the input.
Definition at line 99 of file ads1115.cpp.
     {
         return value * pga_voltage_map.at(m_config.pga) / 32768;
     }
References ADS1115::pga_voltage_map.
write_word()
void ADS1115::ADS1115::write_word (const uint8_t reg_addr, const uint16_t value) const private
Write a 16 bit value to a register.
Parameters
reg_addr The address of the register to be written.
value The 16 bit value to be written.
Definition at line 171 of file ads1115.cpp.
     {
         uint16_t data = util::to_device_repr(value);
         if (0 > i2c_smbus_write_word_data(m_posix_handle, reg_addr, data)) {
             throw std::runtime_error("Error writing value to i2c device.");
         }
     }
References ADS1115::util::to_device_repr().
Member Data Documentation
m_addr
ADDR ADS1115::ADS1115::m_addr private
The i2c bus address of the ADS1115.
Definition at line 25 of file ads1115.hpp.
m_config
Config ADS1115::ADS1115::m_config {} private
The current configuration of the ADS1115.
Definition at line 28 of file ads1115.hpp.
m_posix_handle
const int ADS1115::ADS1115::m_posix_handle private
The linux filedescriptor to the i2c device in use.
Definition at line 22 of file ads1115.hpp.
m_threshold
Threshold ADS1115::ADS1115::m_threshold {} private
The current configuration of the threshold registers.
Definition at line 31 of file ads1115.hpp.
The documentation for this class was generated from the following files:
ads1115/include/ads1115/ads1115.hpp
ads1115/src/ads1115.cpp