ads1115: ADS1115::util Namespace Reference
ADS1115::util Namespace Reference
Functions
template<class To , class From >
std::enable_if_t< sizeof(To)==sizeof(From) &&std::is_trivially_copyable_v< From > &&std::is_trivially_copyable_v< To >, To > bit_cast (const From &src) noexcept
template<class T >
std::enable_if_t< sizeof(T)==2, T > byte_swap (const T value)
template<class T >
std::enable_if_t< sizeof(T)==2, T > to_device_repr (const T value)
template<class T >
std::enable_if_t< sizeof(T)==2, T > from_device_repr (const T value)
Function Documentation
bit_cast()
template<class To , class From > std::enable_if_t< sizeof(To) == sizeof(From) && std::is_trivially_copyable_v<From> && std::is_trivially_copyable_v<To>, To> ADS1115::util::bit_cast (const From & src) noexcept
Definition at line 17 of file bit.hpp.
     {
         static_assert(
             std::is_trivially_constructible_v<To>,
             "This implementation additionally requires destination type to be trivially "
             "constructible");
         To dst;
         std::memcpy(&dst, &src, sizeof(To));
         return dst;
     }
byte_swap()
template<class T > std::enable_if_t<sizeof(T) == 2, T> ADS1115::util::byte_swap (const T value)
Definition at line 30 of file bit.hpp.
     {
         return static_cast<T>(((value & 0xff) << 8) | ((value & 0xff00) >> 8));
     }
Referenced by to_device_repr().
from_device_repr()
template<class T > std::enable_if_t<sizeof(T) == 2, T> ADS1115::util::from_device_repr (const T value)
Definition at line 45 of file bit.hpp.
     {
         return to_device_repr(value);
     }
References to_device_repr().
Referenced by ADS1115::ADS1115::read_word().
to_device_repr()
template<class T > std::enable_if_t<sizeof(T) == 2, T> ADS1115::util::to_device_repr (const T value)
Definition at line 36 of file bit.hpp.
     {
         if constexpr (std::endian::native != std::endian::big) {
             return byte_swap(value);
         }
         return value;
     }
References byte_swap().
Referenced by from_device_repr(), and ADS1115::ADS1115::write_word().