ads1115: tests/src/ads1115.cpp File Reference
ads1115.cpp File Reference
#include "ads1115/ads1115.hpp"
#include "ads1115/config.hpp"
#include "ads1115/parameters.hpp"
#include <gtest/gtest.h>
Functions
TEST (ads1115, DISABLED_create)
TEST (ads1115, DISABLED_getRegConfig)
TEST (ads1115, DISABLED_getRegThreshold)
Function Documentation
TEST() [1/3]
TEST (ads1115 , DISABLED_create)
Definition at line 12 of file ads1115.cpp.
 {
     ADS1115::ADS1115 ads { 1, ADS1115::ADDR::GND };
     ASSERT_EQ(ads.getADDR(), ADS1115::ADDR::GND);
 }
References ADS1115::GND.
TEST() [2/3]
TEST (ads1115 , DISABLED_getRegConfig)
Definition at line 18 of file ads1115.cpp.
 {
     ADS1115::ADS1115 ads(1, ADS1115::ADDR::GND);
     ads.reset();
     ADS1115::Config def_config {};
     ASSERT_EQ(ads.getRegConfig().mux, ADS1115::MUX::AIN0_AIN1);
     ASSERT_EQ(ads.getRegConfig().pga, ADS1115::PGA::FS_2_048);
     ASSERT_EQ(ads.getRegConfig().mode, ADS1115::MODE::SINGLE_CONV);
     ASSERT_EQ(ads.getRegConfig().data_rate, ADS1115::DR::SPS_128);
     ASSERT_EQ(ads.getRegConfig().comp_mode, ADS1115::COMP_MODE::TRAD_COMP);
     ASSERT_EQ(ads.getRegConfig().comp_pol, ADS1115::COMP_POL::LOW);
     ASSERT_EQ(ads.getRegConfig().comp_lat, ADS1115::COMP_LAT::NON_LATCHING);
     ASSERT_EQ(ads.getRegConfig().comp_que, ADS1115::COMP_QUE::DISABLE_COMP);
 }
References ADS1115::AIN0_AIN1, ADS1115::Config::comp_lat, ADS1115::Config::comp_mode, ADS1115::Config::comp_pol, ADS1115::Config::comp_que, ADS1115::Config::data_rate, ADS1115::DISABLE_COMP, ADS1115::FS_2_048, ADS1115::ADS1115::getRegConfig(), ADS1115::GND, ADS1115::LOW, ADS1115::Config::mode, ADS1115::Config::mux, ADS1115::NON_LATCHING, ADS1115::Config::pga, ADS1115::ADS1115::reset(), ADS1115::SINGLE_CONV, ADS1115::SPS_128, and ADS1115::TRAD_COMP.
TEST() [3/3]
TEST (ads1115 , DISABLED_getRegThreshold)
Definition at line 34 of file ads1115.cpp.
 {
     ADS1115::ADS1115 ads(1, ADS1115::ADDR::GND);
     ads.reset();
     ASSERT_EQ(ads.getRegThreshold().getHigh(), 32767);
     ASSERT_EQ(ads.getRegThreshold().getLow(), -32768);
 }
References ADS1115::Threshold::getHigh(), ADS1115::Threshold::getLow(), ADS1115::ADS1115::getRegThreshold(), ADS1115::GND, and ADS1115::ADS1115::reset().